name: 'Run Cypress tests'
on: [deployment_status]
env:
  RUN_CYPRESS: false # set it to true on release (once password protection is gone)
jobs:
  e2e:
    if: github.event.deployment_status.state == 'success' && env.RUN_CYPRESS == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Cypress
        uses: cypress-io/github-action@v4
        env:
          CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_SECRET }}
          CYPRESS_RETRIES: 1
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          retention-days: 1
          path: |
            cypress/videos
